CREATE TABLE JOBB
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    STATUS        VARCHAR(50)  DEFAULT 'KLAR'            NOT NULL,
    TYPE          VARCHAR(50)                            NOT NULL,
    SAK_ID        BIGINT NULL,
    BEHANDLING_ID BIGINT NULL,
    parameters    text NULL,
    payload       text NULL,
    NESTE_KJORING TIMESTAMP(3)                           NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_JOBB_STATUS_SAK_BEHANDLING ON JOBB (STATUS, SAK_ID, BEHANDLING_ID, NESTE_KJORING);
CREATE INDEX IDX_JOBB_SAK ON JOBB (SAK_ID);
CREATE INDEX IDX_JOBB_BEHANDLING ON JOBB (BEHANDLING_ID);
CREATE INDEX IDX_JOBB_SAK_BEHANDLING ON JOBB (SAK_ID, BEHANDLING_ID);
CREATE INDEX IDX_JOBB_STATUS ON JOBB (STATUS);
CREATE INDEX IDX_JOBB_TYPE ON JOBB (TYPE);
CREATE INDEX IDX_JOBB_STATUS_NESTE_KJORING ON JOBB (STATUS, NESTE_KJORING);
CREATE INDEX IDX_JOBB_NESTE_KJORING ON JOBB (NESTE_KJORING);
CREATE INDEX IDX_JOBB_NESTE_KJORING_SAK_BEHANDLING ON JOBB (SAK_ID, BEHANDLING_ID, NESTE_KJORING);

CREATE TABLE JOBB_HISTORIKK
(
    ID            BIGSERIAL                              NOT NULL PRIMARY KEY,
    JOBB_ID       BIGINT                                 NOT NULL REFERENCES JOBB (ID),
    STATUS        VARCHAR(50)                            NOT NULL,
    FEILMELDING   TEXT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IDX_JOBB_HISTORIKK_ID_STATUS ON JOBB_HISTORIKK (JOBB_ID, STATUS);
CREATE INDEX IDX_JOBB_HISTORIKK_STATUS ON JOBB_HISTORIKK (STATUS);
CREATE INDEX IDX_JOBB_HISTORIKK_TID ON JOBB_HISTORIKK (OPPRETTET_TID);
CREATE INDEX IDX_JOBB_HISTORIKK_JOBB_ID ON JOBB_HISTORIKK (JOBB_ID);

-- TEST TABELLER

CREATE TABLE TEST_TABLE
(
    ID    BIGSERIAL NOT NULL PRIMARY KEY,
    VALUE TEXT      NOT NULL
);

CREATE TABLE ORDER_TABLE
(
    ID            BIGSERIAL NOT NULL PRIMARY KEY,
    VALUE         TEXT      NOT NULL,
    TRAD_NAVN     TEXT      NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
)